config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :scores, only: [:create, :index, :show]
  root 'scores#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def prevent_snooping
    authenticate_or_request_with_http_basic do |username, password|
      password == Rails.configuration.x.password
    end
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  skip_before_action :verify_authenticity_token
  # before_action :prevent_snooping, only: [:index, :create]

  def index
    @scores = Score.all
  end

  def create
    Score.find_or_create_by(name: score_attributes[:name]).update(score_attributes)
    head 201
  end

  def show
    @score = Score.find(params[:id])
  end

  private

  def score_attributes
    params.require(:score).permit(:name, holes: [:body, :incomplete])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hole_score(data)
    if data['incomplete']
      '-'
    else
      data['body'].chars.count
    end
  rescue
    '-'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolfScores</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/tablesorter@2.31.1/dist/js/jquery.tablesorter.combined.min.js" ></script>
  </head>

  <body>
    <div class="container" >
      <%= yield %>
    </div>
    <script>
      $(document).on("turbolinks:load", function() {
        $('code').each(function(i, block) {
          console.log("highlighting", block);
          hljs.highlightBlock(block);
        });
        $("table").tablesorter();
      });
    </script>
  </body>
</html>

app/views/scores/index.html.erb
<h1>Scores</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Team</th>
      <% 1.upto(Rails.configuration.x.number_of_holes) do |hole| %>
        <th>Hole <%= hole %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <th><%= link_to score.name, score %></th>
        <% 1.upto(Rails.configuration.x.number_of_holes) do |hole| %>
          <td><%= link_to hole_score(score.holes[hole.to_s]), score_path(score, hole: hole) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scores/show.html.erb
<h1><%= @score.name %></h1>

<% if params[:hole]
  holes = [params[:hole]]
else
  holes = 1.upto(Rails.configuration.x.number_of_holes).to_a
end
%>
<% holes.each do |hole| %>
  <section class="hole">
  <% body = @score.holes[hole.to_s]['body'] %>
  <h2>Hole <%= hole %> <small class='text-muted'>Score: <%= body.chars.count %></small></h2>
  <code class="ruby">
<%= body.gsub("\n",";") %>
  </code>
  </section>
<% end %>